language: csharp
mono: none
dotnet: 2.1.403
solution: TravisCore.sln
install:
    - dotnet restore
script:
    - dotnet build
    - dotnet test --logger "console;verbosity=detailed" ./TravisParse/bin/Debug/TravisParse.dll
  