language: csharp
mono: none
dotnet: 2.1.403
solution: TravisCore.sln
install:
    - dotnet restore
script:
    - dotnet build
    - cd minicover
    - dotnet minicover instrument --workdir ../ --assemblies TravisParse/**/bin/**/TravisParse.dll -- sources src/**/*.cs
    - dotnet minicover reset
    - cd ..
    - dotnet test --no-build ./TravisParse/TravisParse.csproj
    
  