language: csharp
mono: none
dotnet: 2.1.403
solution: TravisCore.sln
install:
    - dotnet restore
    - dotnet tool install -g coveralls.net --version 1.0.0    
script:
    - dotnet build
    - cd minicover
    - dotnet minicover instrument --workdir ../ --assemblies TravisParse/**/bin/**/TravisParse.dll --sources SharpGedParse/SharpGedParser/**/*.cs
    - dotnet minicover reset
    - cd ..
    - dotnet test --no-build ./TravisParse/TravisParse.csproj
    - cd minicover
    - dotnet minicover report --workdir ../ --threshold 75
    - cd ..
    - dotnet csmacnz.coveralls --help
  