language: csharp
mono: none
dotnet: 2.1.403
solution: TravisCore.sln
install:
    - setfont /usr/share/consolefonts/Lat2-Fixed18.psf.gz
    # - ls /usr/share/consolefonts
    # - cat /etc/default/console-setup
    - dotnet restore
    - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools   
script:
    - dotnet build
    - cd minicover
    - dotnet minicover instrument --workdir ../ --assemblies TravisParse/**/bin/**/TravisParse.dll --sources SharpGedParse/SharpGedParser/**/*.cs
    - dotnet minicover reset
    - cd ..
    - dotnet test --no-build ./TravisParse/TravisParse.csproj
    - cd minicover
    - dotnet minicover report --workdir ../ --threshold 75
    - dotnet minicover coverallsreport --help
#    - dotnet minicover coverallsreport --workdir ../ \
#                                       --service-name "travis-ci" \
#                                       --service-job-id "$TRAVIS_JOB_ID"
#    - cd ..
#    - tools/csmacnz.Coveralls --help
