language: csharp
mono: none
dotnet: 2.1.403
solution: TravisCore.sln
install:
    - dotnet restore
script:
    - dotnet build
    - cd minicover
    - dotnet minicover instrument --workdir ../ --assemblies TravisWrite/**/bin/**/TravisWrite.dll --sources SharpGedParse/SharpGedWriter/**/*.cs --exclude-sources SharpGedParse/SharpGedWriter/**/Tests/*.cs
    - dotnet minicover reset
    - cd ..
    - dotnet test --no-build ./TravisWrite/TravisWrite.csproj
    - cd minicover
    - dotnet minicover report --workdir ../ --threshold 95
    - dotnet minicover coverallsreport --root-path ../ --workdir ../ --service-name "travis-ci" --service-job-id "$TRAVIS_JOB_ID" --branch TravisWriter
#    - cd ..
#    - tools/csmacnz.Coveralls --help
